# SAM CLI default deploy parameters for this service stack.
version = 0.1
[default.deploy.parameters]
stack_name = "updamon-backend"
resolve_s3 = true
s3_prefix = "updamon-backend"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
